### PR TITLE
ray: simplify nan checking by creating a macro.

### LINKED ISSUE #223: Wrong results for ray/box intersection on systems without isnanf
### Experienced behavior
On systems without `isnanf`, such as those using musl instead of glibc, sometimes a ray is wrongly detected to intersect a box. This is breaking picking in gnome-shell on Alpine Linux or Void Linux (when using musl): https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/3976

This is due to a typo in the non-`HAVE_ISNANF` code path in `graphene_ray_intersect_box()`: https://github.com/ebassi/graphene/blob/a28aacb00a103ac616374c025406f629ed6a5289/src/graphene-ray.c#L566

This should be `ty_max < tx_max` as is already correctly done in the `HAVE_ISNANF` code path.

### Expected behavior
Only detect an intersection when there is one.

### Steps to reproduce
Try running the following program with glibc and with musl:

```
#include <graphene.h>

int main (int argc, char *argv[]) {
    graphene_point3d_t min, max;
    graphene_box_t box;

    graphene_point3d_init (&min, -14.001682, 50.620972, -50.368336);
    graphene_point3d_init (&max, 12.924316, 72.161774, -50.368336);
    graphene_box_init (&box, &min, &max);
   
    graphene_point3d_t o;
    graphene_vec3_t d;
    graphene_ray_t r;

    graphene_point3d_init (&o, 0.0, 0.0, 0.0);
    graphene_vec3_init (&d, -0.187414, 0.804487, -0.563628);

    graphene_ray_init (&r, &o, &d);

    if (graphene_ray_intersects_box (&r, &box)) {
        return 1;
    }

    return 0;
}
```

### Operating system in use
Fedora 34, but graphene compiled against musl instead of glibc to test this behavior.

### SIMD implementation in use
SSE2

### PR DESCRIPTION
**Pull request by ericonr**
Avoids the #ifdef forest and code duplication resulting from it.
There was mismatch in the two code paths, see [1] and [2], and this
commit avoids repeating the same mistake.

[1] https://github.com/ebassi/graphene/issues/223
[2] https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/3976

Fixes #223

### CODE REVIEW

**Comment by Gottox** [comment]
Be aware of this comment: https://github.com/ebassi/graphene/pull/174#issuecomment-561325167

**Comment by ericonr** [comment]
@Gottox I am still using `isnanf` when available, just avoiding the code duplication resulting from how it was originally implemented.

File: src/graphene-ray.c [hunk 1]
```diff
@@ -53,8 +53,9 @@
 #include <float.h>
 
 #if defined(_M_X64) && ! defined(isnanf)
```
Comment (mixi) [inline src/graphene-ray.c:55]: You are piggybacking a special case instead of handling it the same way as before. This goes against what you suggested in https://github.com/ebassi/graphene/pull/225#issuecomment-817358342.

This should be:
```
#if defined(_M_X64) && !defined(isnanf)
# define my_isnan(x) _isnanf(x)
#elif HAVE_ISNANF
# define my_isnan(x) isnanf(x)
#else
# define my_isnan(x) isnan(x)
#endif
```

Comment (ericonr) [reply src/graphene-ray.c:55]: Thanks, I had only grepped for `HAVE_ISNANF`. I have now seen https://github.com/ebassi/graphene/blob/master/meson.build#L172

**Comment by ericonr** [comment]
Ping?

File: src/graphene-ray.c [hunk 2]
```diff
@@ -53,8 +53,11 @@
...
-# define isnanf(x) _isnanf(x)
-# define HAVE_ISNANF
+# define my_isnan(x) _isnanf(x)
```
Comment (ebassi) [inline src/graphene-ray.c:56]: Would it be possible to hoist this whole thing into `graphene-private.h` and call it `graphene_isnan()` instead? Something like:

```c
#if defined(_M_X64) && !defined(isnanf)
# define graphene_isnan(x) _isnanf(x)
#elif defined(HAVE_ISNANF)
# define graphene_isnan(x) isnanf(x)
#else
# define graphene_isnan(x) isnan(x)
#endif
```

**Review by ebassi — CHANGES_REQUESTED** [review]
Thanks for your contribution!

File: src/graphene-ray.c (hunk 2 above)
Comment (ericonr) [reply src/graphene-ray.c:56]: Definitely, I did it in the file directly because it was the only place using `isnan`.

Will let you know when I'm done.

Comment (ericonr) [reply src/graphene-ray.c]: Done, thanks!
